In [1]:
from src.data_management.loaders import ReadRawStepLoader, MergeRawStepLoader, ProductSplitStepLoader, UnderlyingStepLoader, VolatilityStepLoader

In [2]:
ccontracts_c2_df, tgentrades_df, rates_df = ReadRawStepLoader.load()

100%|██████████| 6/6 [03:09<00:00, 31.65s/it]
100%|██████████| 6/6 [02:12<00:00, 22.09s/it]
2026-03-10 00:16:40,467 | INFO | src.data_management.builders.read_raw_step_builders | CContractsC2Database (with shape (2269342, 6)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\raw_data\CCONTRACTS_C2.csv.
2026-03-10 00:18:12,774 | INFO | src.data_management.builders.read_raw_step_builders | TgentradesDatabase (with shape (16468230, 10)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\raw_data\TGENTRADES.csv.
2026-03-10 00:18:15,358 | INFO | src.data_management.builders.read_raw_step_builders | RatesDatabase (with shape (6953,)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\raw_data\RATES_DATABASE.csv.

In [2]:
trade_ibex_db = MergeRawStepLoader.load()

2026-03-10 02:30:06,691 | INFO | src.data_management.builders.merge_raw_step_builders | There are 310856 trades with missing maturities,corresponding to 1054 different (SessionDate, ContractCode) pairs. Imputing missing maturities based on this pair.
2026-03-10 02:30:10,220 | INFO | src.data_management.builders.merge_raw_step_builders | There are 7641 option trades with missing strike price,corresponding to 85 different ContractCode. Imputing missing strikes.
2026-03-10 02:32:39,106 | INFO | src.data_management.builders.merge_raw_step_builders | TradeIbexDatabase (with shape (16468230, 13)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\merge_raw_data\TRADE_IBEX_DB.csv.

In [3]:
options_trade_ibex_db, futures_trade_ibex_db, options_underlying_ibex_db = ProductSplitStepLoader.load()

2026-03-10 02:13:16,197 | INFO | src.data_management.builders.product_split_step_builders | OptionsTradeIbexDatabase (with shape (428448, 12)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\product_split_data\options_TRADES_DB.csv.
2026-03-10 02:14:09,736 | INFO | src.data_management.builders.product_split_step_builders | FuturesTradeIbexDatabase (with shape (16039782, 12)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\product_split_data\futures_TRADES_DB.csv.
2026-03-10 02:14:10,392 | INFO | src.data_management.builders.product_split_step_builders | OptionsUnderlyingIbexDatabase (with shape (4462, 3)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\product_split_data\OPTION_UNDERLYING_DB.csv.

In [2]:
options_trade_underlying_ibex_db = UnderlyingStepLoader.load()

2026-03-10 02:54:05,432 | INFO | src.data_management.builders.underlying_step_builders | OptionsTradeUnderlyingIbexDatabase (with shape (406690, 15)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\underlying_data\OPTION_TRADES_UNDERLYING_DB.csv.

In [5]:
options_trade_underlying_ibex_db[options_trade_underlying_ibex_db["UnderlyingExecDateTime"].isna()].shape[0]

KeyError: 'UnderlyingExecDateTime'

In [11]:
options_trade_underlying_ibex_db [options_trade_underlying_ibex_db["OptionContractCode"] == "CIBX 8100Q22"]

,OptionContractCode,FutureContractCode,UnderlyingPrice,SessionDate,MarketCode,TradeExecID,TradePriceOption,Quantity,TradeType,StrikePrice,MaturityDate,ExecTime,ExecDateTime,TimeToExpiration,UnderlyingExecDateTime
424988,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-10,M3,100139791,439.0,1,M,8100.0,<NA>,16:24:35.841158,2022-06-10 16:24:35.841158,70.19125183844908,NaT
424989,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-10,M3,100139792,440.0,1,M,8100.0,<NA>,16:24:49.062896,2022-06-10 16:24:49.062896,70.19109880907408,NaT
425559,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-13,M3,100140543,347.0,1,M,8100.0,<NA>,17:29:28.952146,2022-06-13 17:29:28.952146,67.14619268349537,NaT
426115,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-15,M3,100141322,330.0,1,M,8100.0,<NA>,13:59:18.028144,2022-06-15 13:59:18.028144,65.29215245203703,NaT
426460,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-16,M3,100141730,270.0,1,M,8100.0,<NA>,16:31:44.559738,2022-06-16 16:31:44.559738,64.18628981784722,NaT
426486,CIBX 8100Q22,FIBXQ2,<NA>,2022-06-16,M3,100141766,270.0,1,M,8100.0,<NA>,17:14:58.068042,2022-06-16 17:14:58.068042,64.156272360625,NaT
426784,CIBX 8100Q22,FIBXQ2,8017.0,2022-06-20,M3,100142201,310.0,1,M,8100.0,2022-08-19 21:00:00,10:34:42.205015,2022-06-20 10:34:42.205015,60.43423373825232,2022-06-17 09:48:32.818727
426792,CIBX 8100Q22,FIBXQ2,8017.0,2022-06-20,M3,100142214,313.0,1,M,8100.0,2022-08-19 21:00:00,11:03:40.538548,2022-06-20 11:03:40.538548,60.41411413717592,2022-06-17 09:48:32.818727
427519,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143325,275.0,1,M,8100.0,2022-08-19 21:00:00,11:46:45.965589,2022-06-24 11:46:45.965589,56.38419021309028,2022-06-24 08:28:19.454370
427531,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143354,285.0,1,M,8100.0,2022-08-19 21:00:00,13:08:52.730572,2022-06-24 13:08:52.730572,56.32716747023148,2022-06-24 08:28:19.454370
427542,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143380,295.0,1,M,8100.0,2022-08-19 21:00:00,13:56:59.305264,2022-06-24 13:56:59.305264,56.29375804092593,2022-06-24 08:28:19.454370
427561,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143422,305.0,1,M,8100.0,2022-08-19 21:00:00,16:00:58.508310,2022-06-24 16:00:58.508310,56.20765615381944,2022-06-24 08:28:19.454370
427565,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143430,315.0,1,M,8100.0,2022-08-19 21:00:00,16:02:25.112005,2022-06-24 16:02:25.112005,56.20665379623843,2022-06-24 08:28:19.454370
427577,CIBX 8100Q22,FIBXQ2,8058.0,2022-06-24,M3,100143453,325.0,1,M,8100.0,2022-08-19 21:00:00,16:15:30.921718,2022-06-24 16:15:30.921718,56.19755877641203,2022-06-24 08:28:19.454370

In [8]:
options_underlying_ibex_db[options_underlying_ibex_db["OptionContractCode"] == "CIBX 8100Q22"]

     OptionContractCode         MaturityDate FutureContractCode
4429       CIBX 8100Q22  2022-08-19 21:00:00             FIBXQ2

In [9]:
futures_trade_ibex_db[futures_trade_ibex_db["FutureContractCode"] == "FIBXQ2"]

,FutureContractCode,SessionDate,MarketCode,TradeExecID,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate,ExecDateTime,TimeToExpiration
16381814,FIBXQ2,2022-06-17,M3,007549821,09:48:32.818727,8017.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-17 09:48:32.818727,63.466286820289355
16403412,FIBXQ2,2022-06-20,M3,007574637,19:59:03.329181,8208.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-20 19:59:03.329181,60.04232257892362
16405250,FIBXQ2,2022-06-21,M3,007576761,09:31:08.226706,8250.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-21 09:31:08.226706,59.47837700571759
16406823,FIBXQ2,2022-06-21,M3,007578574,11:32:04.288285,8211.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-21 11:32:04.288285,59.3943948115162
16406883,FIBXQ2,2022-06-21,M3,007578647,11:41:04.457562,8211.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-21 11:41:04.457562,59.38814285229167
16410285,FIBXQ2,2022-06-21,M3,007582531,16:58:16.066316,8156.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-21 16:58:16.066316,59.16786960282407
16411551,FIBXQ2,2022-06-21,M3,007583917,18:11:00.172193,8137.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-21 18:11:00.172193,59.11735911813658
16413280,FIBXQ2,2022-06-22,M3,007586108,09:08:04.019939,8012.0,2,M,<NA>,2022-08-19 21:00:00,2022-06-22 09:08:04.019939,58.49439791737269
16420926,FIBXQ2,2022-06-22,M3,007594601,16:36:14.220709,8093.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-22 16:36:14.220709,58.183168741793985
16421476,FIBXQ2,2022-06-22,M3,007595239,17:04:01.628640,8078.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-22 17:04:01.628640,58.163870038888895
16435127,FIBXQ2,2022-06-23,M3,007610381,17:31:36.081033,8026.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-23 17:31:36.081033,57.14472128434028
16436229,FIBXQ2,2022-06-23,M3,007611661,19:38:38.837922,7980.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-23 19:38:38.837922,57.05649493145833
16436561,FIBXQ2,2022-06-24,M3,007612128,08:28:19.454370,8058.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-24 08:28:19.454370,56.52199705590277
16464237,FIBXQ2,2022-06-28,M3,007643300,15:31:20.254315,8253.0,2,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:20.254315,52.228237797280094
16464239,FIBXQ2,2022-06-28,M3,007643303,15:31:20.318633,8253.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:20.318633,52.228237052858795
16464241,FIBXQ2,2022-06-28,M3,007643306,15:31:20.346099,8253.0,2,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:20.346099,52.22823673496527
16464244,FIBXQ2,2022-06-28,M3,007643310,15:31:20.989871,8253.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:20.989871,52.22822928390046
16464257,FIBXQ2,2022-06-28,M3,007643324,15:31:35.986369,8248.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:35.986369,52.22805571332176
16464263,FIBXQ2,2022-06-28,M3,007643331,15:31:47.573520,8248.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:47.573520,52.227921602777776
16464267,FIBXQ2,2022-06-28,M3,007643336,15:31:47.573801,8248.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:47.573801,52.227921599525466
16464269,FIBXQ2,2022-06-28,M3,007643339,15:31:47.574049,8248.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:47.574049,52.227921596655094
16464271,FIBXQ2,2022-06-28,M3,007643342,15:31:47.602543,8248.0,1,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:47.602543,52.227921266863426
16464273,FIBXQ2,2022-06-28,M3,007643345,15:31:47.602715,8248.0,2,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:31:47.602715,52.22792126487269
16464622,FIBXQ2,2022-06-28,M3,007643735,15:48:43.679666,8267.0,2,M,<NA>,2022-08-19 21:00:00,2022-06-28 15:48:43.679666,52.21616111497685
16464997,FIBXQ2,2022-06-28,M3,007644168,16:08:52.347474,8242.0,1,S,<NA>,2022-08-19 21:00:00,2022-06-28 16:08:52.347474,52.2021719042361

In [12]:
options_trade_ibex_db[options_trade_ibex_db["OptionContractCode"] == "CIBX 8100Q22"]

,OptionContractCode,SessionDate,MarketCode,TradeExecID,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate,ExecDateTime,TimeToExpiration
16275472,CIBX 8100Q22,2022-06-10,M3,100139791,16:24:35.841158,439.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-10 16:24:35.841158,70.19125183844908
16275475,CIBX 8100Q22,2022-06-10,M3,100139792,16:24:49.062896,440.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-10 16:24:49.062896,70.19109880907408
16298017,CIBX 8100Q22,2022-06-13,M3,100140543,17:29:28.952146,347.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-13 17:29:28.952146,67.14619268349537
16343999,CIBX 8100Q22,2022-06-15,M3,100141322,13:59:18.028144,330.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-15 13:59:18.028144,65.29215245203703
16373031,CIBX 8100Q22,2022-06-16,M3,100141730,16:31:44.559738,270.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-16 16:31:44.559738,64.18628981784722
16374589,CIBX 8100Q22,2022-06-16,M3,100141766,17:14:58.068042,270.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-16 17:14:58.068042,64.156272360625
16398058,CIBX 8100Q22,2022-06-20,M3,100142201,10:34:42.205015,310.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-20 10:34:42.205015,60.43423373825232
16398450,CIBX 8100Q22,2022-06-20,M3,100142214,11:03:40.538548,313.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-20 11:03:40.538548,60.41411413717592
16440326,CIBX 8100Q22,2022-06-24,M3,100143325,11:46:45.965589,275.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 11:46:45.965589,56.38419021309028
16441218,CIBX 8100Q22,2022-06-24,M3,100143354,13:08:52.730572,285.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 13:08:52.730572,56.32716747023148
16441749,CIBX 8100Q22,2022-06-24,M3,100143380,13:56:59.305264,295.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 13:56:59.305264,56.29375804092593
16443347,CIBX 8100Q22,2022-06-24,M3,100143422,16:00:58.508310,305.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 16:00:58.508310,56.20765615381944
16443501,CIBX 8100Q22,2022-06-24,M3,100143430,16:02:25.112005,315.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 16:02:25.112005,56.20665379623843
16444115,CIBX 8100Q22,2022-06-24,M3,100143453,16:15:30.921718,325.0,1,M,8100.0,2022-08-19 21:00:00,2022-06-24 16:15:30.921718,56.19755877641203

In [1]:
from src.data_management.loaders import ReadRawStepLoader, MergeRawStepLoader, ProductSplitStepLoader, UnderlyingStepLoader, VolatilityStepLoader

In [2]:
options_trade_volatility_ibex_db = VolatilityStepLoader.load()

OverflowError: date value out of range

In [ ]:
from src.config.config import (
    config,
    RAW_DATA_STEP_DIR_PATH,
    MERGE_RAW_DATA_STEP_DIR_PATH,
    PRODUCT_SPLIT_DATA_STEP_DIR_PATH,
)

from src.data_management.read_raw_step.ccontracts_c2_loader import CContractsC2Loader
from src.data_management.read_raw_step.tgentrades_loader import TgentradesLoader

from src.data_management.merge_raw_step.trade_ibex_loader import TradeIbexLoader
# from src.data_management.product_split_step.trades_by_contract_type_loader import trades_by_contract_type
# from src.data_management.product_split_step.options_future_contract_relationship_loader import options_future_contract_relationship
# from src.data_management.underlying_step.options_trades_with_underlying_loader import build_options_trade_underlying
from src.enums.data_enums.contract_type_enum import ContractTypeEnum

In [ ]:
futures_mask = ccontracts_c2_df["ContractCode"].str.len()==6
futures = ccontracts_c2_df[futures_mask]
options = ccontracts_c2_df[~futures_mask]

if futures[[c for c in futures.columns if c!="StrikePrice"]].isna().any().any():
    print("Futures data is tiene NAs")

if options.isna().any().any():
    print("Options data is tiene NAs")

In [ ]:
# TRADE_IBEX_DATABASE
TradeIbexLoader.load(
    merge_columns=config.data_config.merge_raw_config.merge_columns_list,
    selected_columns_list=config.data_config.merge_raw_config.trade_ibex_columns_list,
)

2026-02-22 01:17:43,362 | INFO | src.data_management.merge_raw_step.trade_ibex_loader | DF (with shape (16468230, 11)) saved in: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\merge_raw_data\TRADE_IBEX_DATABASE.csv.

,SessionDate,MarketCode,TradeExecID,ContractCode,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate,ContractType
0,2017-01-02,M3,FI0050130697,FIBXF7,1900-01-01 09:00:06,9296.0,6,M,<NA>,<NA>,futures
1,2017-01-02,M3,FI0050130698,FIBXF7,1900-01-01 09:00:06,9296.0,1,M,<NA>,<NA>,futures
2,2017-01-02,M3,FI0050130699,FIBXF7,1900-01-01 09:00:06,9296.0,1,M,<NA>,<NA>,futures
3,2017-01-02,M3,FI0050130700,FIBXF7,1900-01-01 09:00:06,9296.0,1,M,<NA>,<NA>,futures
4,2017-01-02,M3,FI0050130701,FIBXF7,1900-01-01 09:00:06,9296.0,1,M,<NA>,<NA>,futures
...,...,...,...,...,...,...,...,...,...,...,...
16468225,2022-06-28,M3,007647891,FIBXN2,1900-01-01 19:59:28.277066,8188.0,1,M,<NA>,2022-07-15,futures
16468226,2022-06-28,M3,007647892,FIBXN2,1900-01-01 19:59:44.393052,8188.0,1,M,<NA>,2022-07-15,futures
16468227,2022-06-28,M3,007647893,FIBXN2,1900-01-01 19:59:47.739983,8186.0,1,M,<NA>,2022-07-15,futures
16468228,2022-06-28,M3,007647894,FIBXN2,1900-01-01 19:59:54.692627,8190.0,1,M,<NA>,2022-07-15,futures
16468229,2022-06-28,M3,007647895,FIBXN2,1900-01-01 19:59:57.914100,8189.0,1,M,<NA>,2022-07-15,futures

In [ ]:
# OPTIONS_TRADE_IBEX_DATABASE & FUTURES_TRADE_IBEX_DATABASE
trades_with_contracts_filename = MERGE_RAW_DATA_STEP_DIR_PATH / f"{config.data_config.merge_raw_config.output_filename}.csv"

dfs = trades_by_contract_type(
    trades_contract_filename=trades_with_contracts_filename,
    )

df_options = dfs["OPTIONS"]
df_futures = dfs["FUTURES"]

Archivo guardado en: C:\Users\danir\Desktop\TFM - Opciones\options-pricing\data\product_split_data\OPTIONS_TRADE_IBEX_DATABASE.csv
Total filas finales: 428448

Archivo guardado en: C:\Users\danir\Desktop\TFM - Opciones\options-pricing\data\product_split_data\FUTURES_TRADE_IBEX_DATABASE.csv
Total filas finales: 16039782

In [ ]:
# OPTIONS_UNDERLYING_IBEX_DATABASE
output_contracts = config.data_config.product_split_config.output_filename_contracts

options_tr_filename = PRODUCT_SPLIT_DATA_STEP_DIR_PATH / f"{ContractTypeEnum.OPTIONS.name}_{output_contracts}.csv"
futures_tr_filename = PRODUCT_SPLIT_DATA_STEP_DIR_PATH / f"{ContractTypeEnum.FUTURES.name}_{output_contracts}.csv"

df = options_future_contract_relationship(
        options_trades_filename=options_tr_filename,
        futures_trades_filename=futures_tr_filename,
    )

Archivo guardado en: C:\Users\danir\Desktop\TFM - Opciones\options-pricing\data\product_split_data\OPTIONS_UNDERLYING_IBEX_DATABASE.csv
Total filas finales: 8187

In [ ]:
# OPTIONS_TRADE_UNDERLYING_IBEX_DATABASE
output_contracts = config.data_config.product_split_config.output_filename_contracts
output_options_underlying = config.data_config.product_split_config.output_filename_relationship

options_tr_filename = PRODUCT_SPLIT_DATA_STEP_DIR_PATH / f"{ContractTypeEnum.OPTIONS.name}_{output_contracts}.csv"
futures_tr_filename = PRODUCT_SPLIT_DATA_STEP_DIR_PATH / f"{ContractTypeEnum.FUTURES.name}_{output_contracts}.csv"
options_underlying_tr_filename = PRODUCT_SPLIT_DATA_STEP_DIR_PATH / f"{output_options_underlying}.csv"

df = build_options_trade_underlying(
        options_trades_filename=options_tr_filename,
        futures_trades_filename=futures_tr_filename,
        options_underlying_filename=options_underlying_tr_filename,
    )

       OptionContractCode SessionDate MarketCode   TradeExecID  \
0            PIBX 5100Z17  2017-01-02         M3  OM0001645362
1            PIBX 5100Z17  2017-01-02         M3  OM0001645362
2            PIBX 5100Z17  2017-01-02         M3  OM0001645362
3            PIBX 5100Z17  2017-01-02         M3  OM0001645362
4            PIBX 5100Z17  2017-01-02         M3  OM0001645362
...                   ...         ...        ...           ...
918814       CIBX 8500N22  2022-06-28         M3     100144011
918815       PIBX 7500N22  2022-06-28         M3     100144012
918816       CIBX 8500N22  2022-06-28         M3     100144013
918817       CIBX 8500N22  2022-06-28         M3     100144014
918818       CIBX 8500N22  2022-06-28         M3     100144015

               ExecTime TradePriceOption Quantity TradeType StrikePrice  \
0       09:03:56.000000             33.0        1         M        <NA>
1       09:03:56.000000             33.0        1         M        <NA>
2       09:03:56.000000             33.0        1         M        <NA>
3       09:03:56.000000             33.0        1         M        <NA>
4       09:03:56.000000             33.0        1         M        <NA>
...                 ...              ...      ...       ...         ...
918814  17:28:12.120873             52.0        1         M      8500.0
918815  17:28:21.709970             11.0        1         M      7500.0
918816  17:29:39.189409             49.0        1         M      8500.0
918817  17:29:58.629091             49.0        3         M      8500.0
918818  17:30:45.051696             49.0        1         M      8500.0

       MaturityDate_x  ... SessionDate_future MarketCode_future  \
0                <NA>  ...         2017-01-02                M3
1                <NA>  ...               <NA>              <NA>
2                <NA>  ...               <NA>              <NA>
3                <NA>  ...               <NA>              <NA>
4                <NA>  ...               <NA>              <NA>
...               ...  ...                ...               ...
918814     2022-07-15  ...         2022-06-28                M3
918815     2022-07-15  ...         2022-06-28                M3
918816     2022-07-15  ...         2022-06-28                M3
918817     2022-07-15  ...         2022-06-28                M3
918818     2022-07-15  ...         2022-06-28                M3

       TradeExecID_future  ExecTime_future UnderelayingPrice Quantity_future  \
0            FI0050130833  09:03:53.000000            9296.0               1
1                    <NA>              NaN              <NA>            <NA>
2                    <NA>              NaN              <NA>            <NA>
3                    <NA>              NaN              <NA>            <NA>
4                    <NA>              NaN              <NA>            <NA>
...                   ...              ...               ...             ...
918814          007645709  17:28:10.680029            8227.0               1
918815          007645710  17:28:13.814459            8227.0               1
918816          007645822  17:29:39.083192            8225.0               1
918817          007645858  17:29:58.586608            8226.0               1
918818          007645914  17:30:44.729817            8224.0               1

       TradeType_future StrikePrice_future MaturityDate  \
0                     M               <NA>         <NA>
1                  <NA>               <NA>         <NA>
2                  <NA>               <NA>         <NA>
3                  <NA>               <NA>         <NA>
4                  <NA>               <NA>         <NA>
...                 ...                ...          ...
918814                M               <NA>   2022-07-15
918815                M               <NA>   2022-07-15
918816                M               <NA>   2022-07-15
918817                M               <NA>   2022-07-15
918818                M               <NA>   2022-07-15

             UnderelayingExecTime
0      2017-01-02 09:03:53.000000
1                             NaT
2                             NaT
3                             NaT
4                             NaT
...                           ...
918814 2022-06-28 17:28:10.680029
918815 2022-06-28 17:28:13.814459
918816 2022-06-28 17:29:39.083192
918817 2022-06-28 17:29:58.586608
918818 2022-06-28 17:30:44.729817

[918819 rows x 23 columns]
Index(['OptionContractCode', 'SessionDate', 'MarketCode', 'TradeExecID',
       'ExecTime', 'TradePriceOption', 'Quantity', 'TradeType', 'StrikePrice',
       'MaturityDate_x', 'ExecDateTime', 'MaturityDate_y',
       'FutureContractCode', 'SessionDate_future', 'MarketCode_future',
       'TradeExecID_future', 'ExecTime_future', 'UnderelayingPrice',
       'Quantity_future', 'TradeType_future', 'StrikePrice_future',
       'MaturityDate', 'UnderelayingExecTime'],
      dtype='str')

Archivo guardado en: C:\Users\danir\Desktop\TFM - Opciones\options-pricing\data\underlying_data\OPTIONS_TRADE_UNDERLYING_IBEX_DATABASE.csv
Total filas finales: 918819

Common functions

In [ ]:
# Custom process
def check_is_header(series: pd.Series) -> bool:
    return series.str.match(r"^[A-Za-z_]+$").all()

def default_custom_process(df: pd.DataFrame) -> pd.DataFrame:
    is_header = check_is_header(df.iloc[0])
    if is_header:
        df = df.iloc[1:, :].reset_index(drop=True)
        
    return df

# Process paths
def get_unique_files(file_list:t.List[Path]) -> t.List[Path]:
    unique_files = {}
    for file in file_list:
        name_without_extension = "".join(file.name.split(".")[:-1])
        date = name_without_extension.split("_")[-1]  # Assuming the date is the last part of the name
        if file.name not in unique_files:
            unique_files[date] = file
    return list(unique_files.values())

# Process datetimes
def prepare_datetime(time_str: str) -> str:
    """ 
    Possible values for time_str: [
        "01/01/3000 9:00:06", 
        "01/01/3000 09:00:06", 
        "09:00:00.000000", 
        "09:00:00:000", 
        "08:00:16.002360"
    ]
    """
    time_str = time_str.split(" ")[-1]
    time_str_split = time_str.split(":")
    time_str_split[0] = f"0{time_str_split[0]}" if len(time_str_split[0]) == 1 else time_str_split[0]

    if len(time_str_split) == 4:
        time_str = f"{time_str_split[0]}:{time_str_split[1]}:{time_str_split[2]}.{time_str_split[3]}"
    elif len(time_str_split) != 3:
        raise ValueError(f"Unexpected time format: {time_str}")
    else:
        time_str = ":".join(time_str_split)

    time_str_split = time_str.split(".")
    if len(time_str_split) == 1:
        time_str = f"{time_str_split[0]}.000000"

    return time_str

# Main function to build raw data
def build_data_raw(
        columns_list:t.List[str],
        selected_columns_dict:t.Dict[str, DataType],
        file_prefix: str,
        custom_processing_func: t.Optional[t.Callable] = default_custom_process
    ) -> pd.DataFrame:

    # Data raw
    data_raw = []

    # For every year, we read each contract type
    for year in tqdm(range(FIRST_YEAR, LAST_YEAR + 1)):
        path_year = Path(f"data/{year}")

        file_list = list(path_year.glob(f"{file_prefix}_*.TXT")) + list(path_year.glob(f"{file_prefix}_*.M3"))
        unique_file_list = get_unique_files(file_list)

        for file in unique_file_list:
            if file.is_file():
                df = pd.read_csv(
                    file,
                    delimiter=";",
                    header=None,
                    dtype="string",
                )

                # Custom process for each case. We can use the default one, which checks if the first row is a header and removes it if so.
                df = custom_processing_func(df=df)

                # Columns
                total_columns = df.shape[1]
                unknown_names = [
                    f"unknown_{i+1}"
                    for i in range(max(0, total_columns - len(columns_list)))
                ]
                column_names = columns_list + unknown_names

                # Assign
                df.columns = column_names

                # Select only relevant columns
                df = df[list(selected_columns_dict.keys())]

                # IBX mask
                IBX_mask = df["ContractCode"].str.contains(
                    ("IBX"),
                    na=False
                )
                df = df[IBX_mask]

                # Convert data types
                for col, dtype in selected_columns_dict.items():
                    if dtype == DataType.DATE:
                        df[col] = pd.to_datetime(df[col], format="%Y%m%d").dt.date    
                    elif dtype == DataType.DATETIME:
                        
                        try:
                            df[col] = df[col].str.strip().str.split(" ").str[-1].apply(prepare_datetime)
                            df[col] = pd.to_datetime(df[col], format="%H:%M:%S.%f")
                        except Exception as e:
                            raise ValueError(f"Unexpected format in column {col}. file: {file.name} Error: {e}")
                    elif dtype == DataType.FLOAT:
                        df[col] = pd.to_numeric(df[col].str.replace(",", "."), downcast="float")
                    elif dtype == DataType.INT:
                        df[col] = pd.to_numeric(df[col], downcast="integer")
                
                # Metadata
                df["Year"] = year
                df["SourceFile"] = file.name
                
                # Join data_raw
                data_raw.append(df)

    # Concatenate final DataFrame
    data_raw = pd.concat(data_raw, ignore_index=True)

    # Save CSV
    output_dir = Path(f"raw_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / f"{file_prefix}.csv"
    data_raw.to_csv(output_file, index=False, encoding="utf-8", sep=";")

    print(f"\nArchivo guardado en: {output_file}")
    print(f"Total filas finales: {len(data_raw)}")

    return data_raw

CCONTRACTS_C2

In [ ]:
CCONTRACTS_C2_COLUMNS_LIST = [
    "SessionDate",                     # 1 Fecha de sesión
    "ClearingHouseCode",               # 2 Código de cámara
    "ContractCode",                    # 3 Código de contrato
    "ContractGroupCode",               # 4 Grupo del contrato
    "ContractTypeCode",                # 5 Tipo del contrato
    "StrikePrice",                     # 6 Precio de ejercicio
    "MaturityDate",                    # 7 Fecha de vencimiento
    "TradingEndDate",                  # 8 Fecha de fin de negociación
    "ExerciseUnderlyingContractCode",  # 9 Código contrato subyacente (ejercicio)
    "MarginUnderlyingContractCode",    # 10 Código contrato subyacente (garantías)
    "ArrayCode",                       # 11 Código de matriz de garantías
    "ExpiryNumber",                    # 12 Nº vencimiento de liquidación
    "OffsetNumber",                    # 13 Nº compensación
    "ExpirySpan",                      # 14 Tipo de vencimiento (S/L)
    "MaturityMonthYear",               # 15 Identificador del vencimiento
    "ISINCode"                         # 16 Código ISIN
]

CCONTRACTS_C2_COLUMNS_SELECTED_DICT = {
    "SessionDate": DataType.DATE,       # 1 Fecha de sesión
    "ContractCode": DataType.TEXT,      # 3 Código de contrato
    "StrikePrice": DataType.FLOAT,      # 6 Precio de ejercicio
    "MaturityDate": DataType.DATE,      # 7 Fecha de vencimiento
}

In [ ]:
# CCONTRACTS_C2
CContractsC2Handler().build_raw_data(
    columns_list=config.data_config.raw_data_config.ccontracts_c2_columns_list,
    selected_columns_dict=config.data_config.raw_data_config.ccontracts_c2_columns_selected_dict,
    file_prefix=config.data_config.raw_data_config.cconctracts_c2_prefix,
)

100%|██████████| 6/6 [01:50<00:00, 18.35s/it]

Archivo guardado en: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\raw_data\CCONTRACTS_C2.csv
Total filas finales: 2520238

,SessionDate,ContractCode,StrikePrice,MaturityDate,Year,SourceFile
0,2017-03-17,FIBXM7,<NA>,2017-06-16,2017,CCONTRACTS_C2_20170317.TXT
1,2017-03-17,FIBXZ7,<NA>,2017-12-15,2017,CCONTRACTS_C2_20170317.TXT
2,2017-03-17,CIBX 8000M17,8000.0,2017-06-16,2017,CCONTRACTS_C2_20170317.TXT
3,2017-03-17,CIBX 7800Z17,7800.0,2017-12-15,2017,CCONTRACTS_C2_20170317.TXT
4,2017-03-17,CIBX 7900Z17,7900.0,2017-12-15,2017,CCONTRACTS_C2_20170317.TXT
...,...,...,...,...,...,...
2520233,2022-06-28,PIBX 9200W4N22,9200.0,2022-07-22,2022,CCONTRACTS_C2_20220628.TXT
2520234,2022-06-28,PIBX 9300W4N22,9300.0,2022-07-22,2022,CCONTRACTS_C2_20220628.TXT
2520235,2022-06-28,PIBX 9400W4N22,9400.0,2022-07-22,2022,CCONTRACTS_C2_20220628.TXT
2520236,2022-06-28,CIBX 9500W4N22,9500.0,2022-07-22,2022,CCONTRACTS_C2_20220628.TXT
2520237,2022-06-28,PIBX 9500W4N22,9500.0,2022-07-22,2022,CCONTRACTS_C2_20220628.TXT

In [ ]:
TGENTRADES_COLUMNS_LIST = [
    "SessionDate",    # 1 Fecha de sesión
    "MarketCode",     # 2 Código de mercado
    "TradeExecID",    # 3 Número de registro de negociación
    "ContractCode",   # 4 Código de contrato
    "ExecTime",       # 5 Hora de ejecución
    "TradePrice",     # 6 Precio
    "Quantity",       # 7 Volumen
    "TradeType"       # 8 Tipo de operación
]

TGENTRADES_COLUMNS_SELECTED_DICT = {
    "SessionDate": DataType.DATE,       # 1 Fecha de sesión
    "MarketCode": DataType.TEXT,        # 2 Código de mercado
    "TradeExecID": DataType.TEXT,       # 3 Número de registro de negociación
    "ContractCode": DataType.TEXT,      # 4 Código de contrato
    "ExecTime": DataType.DATETIME,      # 5 Hora de ejecución
    "TradePrice": DataType.FLOAT,       # 6 Precio
    "Quantity": DataType.INT,           # 7 Volumen
    "TradeType": DataType.TEXT          # 8 Tipo de operación
}

In [ ]:
def tgentrades_custom_process(df: pd.DataFrame) -> pd.DataFrame:
    is_header = check_is_header(df.iloc[0])
    if is_header:
        skip_column_list = [c for c, v in df.iloc[0].items() if v.lower().strip() == "secuencia"]
        df.drop(columns=skip_column_list, inplace=True)
        df = df.iloc[1:, :].reset_index(drop=True)

    return df

In [ ]:
def prepare_datetime(time_str: str) -> str:
    """ 
    Possible values for time_str: [
        "01/01/3000 9:00:06", 
        "01/01/3000 09:00:06", 
        "09:00:00.000000", 
        "09:00:00:000", 
        "08:00:16.002360"
    ]
    """
    time_str = time_str.split(" ")[-1]
    time_str_split = time_str.split(":")
    time_str_split[0] = f"0{time_str_split[0]}" if len(time_str_split[0]) == 1 else time_str_split[0]

    if len(time_str_split) == 4:
        time_str = f"{time_str_split[0]}:{time_str_split[1]}:{time_str_split[2]}.{time_str_split[3]}"
    elif len(time_str_split) != 3:
        raise ValueError(f"Unexpected time format: {time_str}")
    else:
        time_str = ":".join(time_str_split)

    time_str_split = time_str.split(".")
    if len(time_str_split) == 1:
        time_str = f"{time_str_split[0]}.000000"

    return time_str

series = pd.Series(["01/01/3000 9:00:06", "01/01/3000 09:00:06", "09:00:00.000000", "09:00:00:000", "08:00:16.002360"])

series = series.str.split(" ").str[-1].apply(prepare_datetime)

display(series)
pd.to_datetime(series, format="%H:%M:%S.%f")

0    09:00:06.000000
1    09:00:06.000000
2    09:00:00.000000
3       09:00:00.000
4    08:00:16.002360
dtype: object

0   1900-01-01 09:00:06.000000
1   1900-01-01 09:00:06.000000
2   1900-01-01 09:00:00.000000
3   1900-01-01 09:00:00.000000
4   1900-01-01 08:00:16.002360
dtype: datetime64[ns]

In [ ]:
# TGENTRADES
TgentradesHandler().build_raw_data(
    columns_list=config.data_config.raw_data_config.tgentrades_columns_list,
    selected_columns_dict=config.data_config.raw_data_config.tgentrades_columns_selected_dict,
    file_prefix=config.data_config.raw_data_config.tgentrades_prefix,
)

100%|██████████| 6/6 [01:24<00:00, 14.15s/it]

Archivo guardado en: C:\Users\pedro\Documents\Estudios\BME\TFM\options-pricing\data\raw_data\TGENTRADES.csv
Total filas finales: 17197910

,SessionDate,MarketCode,TradeExecID,ContractCode,ExecTime,TradePrice,Quantity,TradeType,Year,SourceFile
0,2017-01-02,M3,FI0050130697,FIBXF7,1900-01-01 09:00:06.000000,9296.0,6,M,2017,TGENTRADES_M3_20170102.TXT
1,2017-01-02,M3,FI0050130698,FIBXF7,1900-01-01 09:00:06.000000,9296.0,1,M,2017,TGENTRADES_M3_20170102.TXT
2,2017-01-02,M3,FI0050130699,FIBXF7,1900-01-01 09:00:06.000000,9296.0,1,M,2017,TGENTRADES_M3_20170102.TXT
3,2017-01-02,M3,FI0050130700,FIBXF7,1900-01-01 09:00:06.000000,9296.0,1,M,2017,TGENTRADES_M3_20170102.TXT
4,2017-01-02,M3,FI0050130701,FIBXF7,1900-01-01 09:00:06.000000,9296.0,1,M,2017,TGENTRADES_M3_20170102.TXT
...,...,...,...,...,...,...,...,...,...,...
17197905,2022-06-28,M3,007647891,FIBXN2,1900-01-01 19:59:28.277066,8188.0,1,M,2022,TGENTRADES_20220628.M3
17197906,2022-06-28,M3,007647892,FIBXN2,1900-01-01 19:59:44.393052,8188.0,1,M,2022,TGENTRADES_20220628.M3
17197907,2022-06-28,M3,007647893,FIBXN2,1900-01-01 19:59:47.739983,8186.0,1,M,2022,TGENTRADES_20220628.M3
17197908,2022-06-28,M3,007647894,FIBXN2,1900-01-01 19:59:54.692627,8190.0,1,M,2022,TGENTRADES_20220628.M3
17197909,2022-06-28,M3,007647895,FIBXN2,1900-01-01 19:59:57.914100,8189.0,1,M,2022,TGENTRADES_20220628.M3

In [ ]:

# Validation helpers and configuration
import json
import datetime as dt
from dataclasses import dataclass, asdict, field

import numpy as np

@dataclass
class ValidationConfig:
    null_threshold_mandatory: float = 0.01
    near_constant_ratio: float = 0.99
    outlier_iqr_factor: float = 3.0
    non_negative_keywords: tuple = ("price", "strike", "qty", "quantity", "amount", "volume", "vol", "count", "number")
    trading_start_time: dt.time = field(default_factory=lambda: dt.time(7, 0))
    trading_end_time: dt.time = field(default_factory=lambda: dt.time(21, 30))
    min_valid_date: dt.date = field(default_factory=lambda: dt.date(1900, 1, 1))
    max_valid_date: dt.date = field(default_factory=lambda: dt.date(2026, 2, 7))
    max_future_maturity_years: int = 10
    max_categorical_cardinality: int = 25
    outlier_min_samples: int = 50
    sample_size: int = 5

@dataclass
class ValidationIssue:
    dataframe: str
    severity: str
    message: str
    columns: t.Optional[t.List[str]] = None
    count: t.Optional[int] = None
    sample: t.Optional[pd.DataFrame] = None

class ValidationResult:
    def __init__(self, dataframe: str):
        self.dataframe = dataframe
        self.issues: t.List[ValidationIssue] = []

    def add(self, severity: str, message: str, columns: t.Optional[t.List[str]] = None, count: t.Optional[int] = None, sample: t.Optional[pd.DataFrame] = None):
        self.issues.append(ValidationIssue(
            dataframe=self.dataframe,
            severity=severity,
            message=message,
            columns=columns,
            count=count,
            sample=sample
        ))

    def summary(self) -> t.Dict[str, int]:
        return {
            "dataframe": self.dataframe,
            "pass": sum(1 for i in self.issues if i.severity == "pass"),
            "warn": sum(1 for i in self.issues if i.severity == "warn"),
            "fail": sum(1 for i in self.issues if i.severity == "fail"),
        }

    def to_frame(self) -> pd.DataFrame:
        rows = []
        for issue in self.issues:
            rows.append({
                "dataframe": issue.dataframe,
                "severity": issue.severity,
                "message": issue.message,
                "columns": ", ".join(issue.columns) if issue.columns else "",
                "count": issue.count,
                "sample": issue.sample.head(5) if isinstance(issue.sample, pd.DataFrame) else issue.sample
            })
        return pd.DataFrame(rows)

    def to_markdown(self) -> str:
        df_repr = self.to_frame()
        try:
            return df_repr.to_markdown(index=False)
        except Exception:
            return df_repr.to_string(index=False)

    def to_json(self) -> str:
        def serialize_issue(issue: ValidationIssue) -> dict:
            payload = asdict(issue)
            if isinstance(issue.sample, pd.DataFrame):
                payload["sample"] = issue.sample.head(5).to_dict(orient="records")
            return payload
        return json.dumps([serialize_issue(i) for i in self.issues], default=str, indent=2)

    def raise_if_failed(self) -> None:
        failed = [i for i in self.issues if i.severity == "fail"]
        if failed:
            messages = "; ".join(i.message for i in failed)
            raise AssertionError(f"Validation failed for {self.dataframe}: {messages}")

In [ ]:

# Generic validation checks

def _sample(df: pd.DataFrame, mask: t.Optional[pd.Series], config: ValidationConfig) -> t.Optional[pd.DataFrame]:
    if mask is None:
        return None
    mask = mask.fillna(False)
    if mask.any():
        return df.loc[mask].head(config.sample_size)
    return None

def matches_dtype(series: pd.Series, expected: DataType) -> bool:
    sample = series.dropna().head(20)
    if expected == DataType.DATE:
        return pd.api.types.is_datetime64_any_dtype(series) or sample.apply(lambda x: isinstance(x, (dt.date, pd.Timestamp))).all()
    if expected == DataType.DATETIME:
        return pd.api.types.is_datetime64_any_dtype(series)
    if expected == DataType.FLOAT:
        return pd.api.types.is_float_dtype(series)
    if expected == DataType.INT:
        return pd.api.types.is_integer_dtype(series)
    if expected == DataType.TEXT:
        return pd.api.types.is_string_dtype(series) or sample.apply(lambda x: isinstance(x, str)).all()
    return True

def infer_non_negative_columns(df: pd.DataFrame, config: ValidationConfig, explicit: t.Optional[t.Iterable[str]] = None) -> t.List[str]:
    explicit = explicit or []
    cols: t.Set[str] = set(explicit)
    for col in df.select_dtypes(include=[np.number]).columns:
        name = col.lower()
        if any(keyword in name for keyword in config.non_negative_keywords):
            cols.add(col)
    return sorted(cols)

def run_generic_checks(
    df: pd.DataFrame,
    df_name: str,
    expected_schema: t.Dict[str, DataType],
    key_columns: t.Optional[t.List[str]],
    mandatory_columns: t.Optional[t.List[str]],
    nullable_columns: t.Optional[t.List[str]],
    config: t.Optional[ValidationConfig] = None,
    explicit_non_negative: t.Optional[t.Iterable[str]] = None,
) -> ValidationResult:
    config = config or ValidationConfig()
    mandatory_columns = mandatory_columns or []
    nullable_columns = nullable_columns or []
    result = ValidationResult(df_name)

    # Schema presence
    missing_cols = [c for c in expected_schema if c not in df.columns]
    if missing_cols:
        result.add("fail", f"Missing expected columns: {missing_cols}", columns=missing_cols)
    else:
        result.add("pass", "All expected columns present", columns=list(expected_schema))
    extra_cols = [c for c in df.columns if c not in expected_schema]
    if extra_cols:
        result.add("warn", f"Unexpected columns present: {extra_cols}", columns=extra_cols)

    # Dtype check
    for col, dtype in expected_schema.items():
        if col not in df.columns:
            continue
        if matches_dtype(df[col], dtype):
            result.add("pass", f"{col} dtype matches {dtype.name}", columns=[col])
        else:
            result.add(
                "fail",
                f"{col} dtype does not match expected {dtype.name}",
                columns=[col],
                sample=df[[col]].head(config.sample_size)
            )

    # Missingness
    null_ratio = df.isna().mean()
    for col in mandatory_columns:
        ratio = float(null_ratio.get(col, 0.0))
        if ratio > config.null_threshold_mandatory:
            result.add(
                "fail",
                f"{col} null ratio {ratio:.3f} above threshold {config.null_threshold_mandatory}",
                columns=[col],
                count=int(df[col].isna().sum()),
                sample=_sample(df, df[col].isna(), config)
            )
        else:
            result.add("pass", f"{col} null ratio OK ({ratio:.3f})", columns=[col])
    for col in nullable_columns:
        ratio = float(null_ratio.get(col, 0.0))
        severity = "warn" if ratio > 0.5 else "pass"
        result.add(severity, f"{col} null ratio {ratio:.3f}", columns=[col], count=int(df[col].isna().sum()))

    # Duplicates
    full_dupes = int(df.duplicated().sum())
    if full_dupes > 0:
        result.add("warn", f"{full_dupes} full-row duplicates detected", count=full_dupes, sample=_sample(df, df.duplicated(), config))
    else:
        result.add("pass", "No full-row duplicates detected")

    if key_columns:
        dup_mask = df.duplicated(subset=key_columns, keep=False)
        dup_count = int(dup_mask.sum())
        severity = "fail" if dup_count > 0 else "pass"
        msg = f"{dup_count} duplicate rows on key {key_columns}" if dup_count else "Key is unique"
        result.add(severity, msg, columns=key_columns, count=dup_count, sample=_sample(df, dup_mask, config))

    # Non-negative numeric columns
    for col in infer_non_negative_columns(df, config, explicit_non_negative):
        if col not in df.columns:
            continue
        negative_mask = df[col] < 0
        negative_mask = negative_mask.fillna(False)
        neg_count = int(negative_mask.sum())
        if neg_count > 0:
            result.add("fail", f"{col} has {neg_count} negative values", columns=[col], count=neg_count, sample=_sample(df, negative_mask, config))
        else:
            result.add("pass", f"{col} has no negative values", columns=[col])

    # Constant / near-constant columns
    for col in df.columns:
        counts = df[col].value_counts(dropna=False)
        if counts.empty:
            continue
        top_ratio = counts.iloc[0] / len(df)
        if top_ratio >= config.near_constant_ratio:
            result.add("warn", f"{col} is constant/near-constant (top ratio {top_ratio:.3f})", columns=[col], sample=counts.head().to_frame())
        else:
            result.add("pass", f"{col} shows variation (top ratio {top_ratio:.3f})", columns=[col])

    # Outliers using IQR
    for col in df.select_dtypes(include=[np.number]).columns:
        series = df[col].dropna()
        if len(series) < config.outlier_min_samples:
            continue
        q1, q3 = series.quantile(0.25), series.quantile(0.75)
        iqr = q3 - q1
        if iqr == 0:
            continue
        lower, upper = q1 - config.outlier_iqr_factor * iqr, q3 + config.outlier_iqr_factor * iqr
        mask = (df[col] < lower) | (df[col] > upper)
        count = int(mask.sum())
        if count > 0:
            result.add("warn", f"{col} has {count} potential outliers (IQR)", columns=[col], count=count, sample=_sample(df, mask, config))
        else:
            result.add("pass", f"{col} has no IQR outliers", columns=[col])

    # String normalization
    string_cols = [c for c in df.columns if pd.api.types.is_string_dtype(df[c])]
    for col in string_cols:
        ser = df[col].dropna().astype(str)
        whitespace_mask = df[col].astype(str).str.match(r"^\s") | df[col].astype(str).str.match(r".*\s$")
        whitespace_mask = whitespace_mask.fillna(False)
        empty_mask = df[col].astype(str).str.len() == 0
        empty_mask = empty_mask.fillna(False)
        if whitespace_mask.any() or empty_mask.any():
            mask = whitespace_mask | empty_mask
            result.add("warn", f"{col} contains leading/trailing whitespace or empty strings", columns=[col], count=int(mask.sum()), sample=_sample(df, mask, config))
        else:
            result.add("pass", f"{col} strings are trimmed and non-empty", columns=[col])

        # Casing consistency for low-cardinality columns
        if ser.nunique() <= config.max_categorical_cardinality:
            lower_unique = ser.str.lower().nunique()
            if lower_unique < ser.nunique():
                result.add("warn", f"{col} has casing inconsistencies", columns=[col], sample=pd.Series(ser.unique()[:config.sample_size]))
            else:
                result.add("pass", f"{col} casing consistent across {ser.nunique()} categories", columns=[col])

    # Date/time sanity (datetime columns)
    for col in df.select_dtypes(include=["datetime64[ns]", "datetime64[ns, tz]"]).columns:
        ser = df[col].dropna()
        if ser.empty:
            continue
        min_val, max_val = ser.min(), ser.max()
        if min_val.tzinfo is not None or max_val.tzinfo is not None:
            result.add("warn", f"{col} contains timezone-aware datetimes; ensure consistency", columns=[col])
        if min_val.date() < config.min_valid_date or max_val.date() > config.max_valid_date:
            result.add("warn", f"{col} outside expected date range [{config.min_valid_date}, {config.max_valid_date}]", columns=[col], sample=ser.describe())
        else:
            result.add("pass", f"{col} within expected date range", columns=[col])

    # Categorical overview (low-cardinality only)
    for col in df.columns:
        try:
            nunique = df[col].nunique(dropna=True)
        except Exception:
            continue
        if nunique <= config.max_categorical_cardinality:
            top = df[col].value_counts(dropna=False).head(config.sample_size)
            result.add("pass", f"Top categories for {col}: {top.to_dict()}", columns=[col])

# Exploratoring
CCONTRSTAT_C2_raw.isna().sum()

Las columnas que después vamos a tomar son las siguientes:
* SessionDate
* ContractCode
* HighPrice
* LowPrice
* FirstPrice
* LastPrice

Para estas, las columnas de precios presentan el mismo númeor de valores nulos, habrá que identificar qué ha ocurrido.

# Construcción TRADE_IBEX_DATABASE

In [ ]:
TRADE_IBEX_DATABASE_MERGED_COLUMNS_LIST = [
    "SessionDate",
    "ContractCode",
]

TRADE_IBEX_DATABASE_COLUMNS_SELECTED_DICT = {
    "SessionDate": DataType.DATE,
    "MarketCode": DataType.TEXT,
    "TradeExecID": DataType.TEXT,
    "ContractCode": DataType.TEXT,
    "ExecTime": DataType.DATETIME,
    "TradePrice": DataType.FLOAT,
    "Quantity": DataType.INT,
    "TradeType": DataType.TEXT,
    "StrikePrice": DataType.FLOAT,
    "MaturityDate": DataType.DATE,
}

In [ ]:
def merge_trade_with_contracts(
        trades_filename: str,
        contracts_filename: str,
        merge_columns: t.List[str],
        selected_columns_dict: t.Dict[str, DataType]
) -> pd.DataFrame:
    
    # Read CSVs
    trades_df = pd.read_csv(
        Path(f"raw_data/{trades_filename}"),
        delimiter=";",
        header=0,
        dtype="string",
    )
    contracts_df = pd.read_csv(
        Path(f"raw_data/{contracts_filename}"),
        delimiter=";",
        header=0,
        dtype="string",
    )

    # Merge
    merged_df = trades_df.merge(
        contracts_df,
        on = merge_columns,
        how = "left",
        suffixes=("", "_contract")
    )

    # Select only relevant columns
    merged_df = merged_df[list(selected_columns_dict.keys())]

    # Save CSV
    output_dir = Path(f"raw_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / f"TRADE_IBEX_DATABASE.csv"
    merged_df.to_csv(output_file, index=False, encoding="utf-8", sep=";")

    print(f"\nArchivo guardado en: {output_file}")
    print(f"Total filas finales: {len(merged_df)}")

    return merged_df

In [ ]:
df = merge_trade_with_contracts(
    trades_filename="TGENTRADES.csv",
    contracts_filename="CCONTRACTS_C2.csv",
    merge_columns=TRADE_IBEX_DATABASE_MERGED_COLUMNS_LIST,
    selected_columns_dict=TRADE_IBEX_DATABASE_COLUMNS_SELECTED_DICT
    )

Processing date column: SessionDate
Processing datetime column: ExecTime
Processing float column: TradePrice
Processing integer column: Quantity
Processing float column: StrikePrice
Processing date column: MaturityDate

Archivo guardado en: raw_data\TRADE_IBEX_DATABASE.csv
Total filas finales: 17197910

In [ ]:
import pandas as pd
from pathlib import Path

    # Excessively future maturity
    future_cutoff = session_dt + pd.DateOffset(years=config.max_future_maturity_years)
    far_future_mask = maturity_dt > future_cutoff
    far_future_count = int(far_future_mask.sum())
    if far_future_count:
        result.add("warn", f"{far_future_count} rows have maturity more than {config.max_future_maturity_years} years after SessionDate", columns=["MaturityDate"], count=far_future_count, sample=_sample(df, far_future_mask, config))
    else:
        result.add("pass", "Maturity horizon within configured limit", columns=["MaturityDate"])

    # Contract code pattern
    non_ibx_mask = ~df["ContractCode"].str.contains("IBX", na=False)
    non_ibx_count = int(non_ibx_mask.sum())
    if non_ibx_count:
        result.add("fail", f"{non_ibx_count} contract codes do not contain 'IBX'", columns=["ContractCode"], count=non_ibx_count, sample=_sample(df, non_ibx_mask, config))
    else:
        result.add("pass", "All contract codes contain 'IBX'", columns=["ContractCode"])

    return result


def validate_tgentrades(
    df: pd.DataFrame,
    contracts_df: t.Optional[pd.DataFrame] = None,
    config: t.Optional[ValidationConfig] = None,
) -> ValidationResult:
    config = config or ValidationConfig()
    expected_schema = {
        "SessionDate": DataType.DATE,
        "MarketCode": DataType.TEXT,
        "TradeExecID": DataType.TEXT,
        "ContractCode": DataType.TEXT,
        "ExecTime": DataType.DATETIME,
        "TradePrice": DataType.FLOAT,
        "Quantity": DataType.INT,
        "TradeType": DataType.TEXT,
        "Year": DataType.INT,
        "SourceFile": DataType.TEXT,
    }
    mandatory_columns = list(expected_schema.keys())
    nullable_columns: t.List[str] = []
    key_columns = ["SessionDate", "TradeExecID"]

    result = run_generic_checks(
        df=df,
        df_name="TGENTRADES",
        expected_schema=expected_schema,
        key_columns=key_columns,
        mandatory_columns=mandatory_columns,
        nullable_columns=nullable_columns,
        config=config,
        explicit_non_negative=["TradePrice", "Quantity"],
    )

    # Quantity strictly positive
    non_positive_qty_mask = df["Quantity"] <= 0
    non_positive_qty_mask = non_positive_qty_mask.fillna(False)
    non_positive_qty = int(non_positive_qty_mask.sum())
    if non_positive_qty:
        result.add("fail", f"{non_positive_qty} trades have non-positive quantity", columns=["Quantity"], count=non_positive_qty, sample=_sample(df, non_positive_qty_mask, config))
    else:
        result.add("pass", "Quantities are strictly positive", columns=["Quantity"])

    # ExecTime within trading hours
    exec_time = pd.to_datetime(df["ExecTime"])
    exec_time_time = exec_time.dt.time
    before_open = exec_time_time < config.trading_start_time
    after_close = exec_time_time > config.trading_end_time
    out_of_hours_mask = before_open | after_close
    out_of_hours = int(out_of_hours_mask.sum())
    if out_of_hours:
        result.add("warn", f"{out_of_hours} rows outside trading hours {config.trading_start_time}-{config.trading_end_time}", columns=["ExecTime"], count=out_of_hours, sample=_sample(df, out_of_hours_mask, config))
    else:
        result.add("pass", "ExecTime within trading hours", columns=["ExecTime"])

    # Contract code pattern
    non_ibx_mask = ~df["ContractCode"].str.contains("IBX", na=False)
    non_ibx_count = int(non_ibx_mask.sum())
    if non_ibx_count:
        result.add("fail", f"{non_ibx_count} trade rows have contract codes without 'IBX'", columns=["ContractCode"], count=non_ibx_count, sample=_sample(df, non_ibx_mask, config))
    else:
        result.add("pass", "All trade contract codes contain 'IBX'", columns=["ContractCode"])

display(TRADE_IBEX_DATABASE)

Archivo final guardado en: raw_data\TRADE_IBEX_DATABASE.csv

,SessionDate,MarketCode,TradeExecID,ContractCode,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate,HighPrice,LowPrice,FirstPrice,LastPrice
0,20170317,M3,FI0050674468,FIBXH7,08:00:26,10166,1,M,NaN,20170317,10226,10142,10166,10216
1,20170317,M3,FI0050674469,FIBXJ7,08:00:26,10129,1,M,NaN,20170421,10231,10101,10129,10224
2,20170317,M3,FI0050674470,FIBXH7,08:00:26,10166,1,M,NaN,20170317,10226,10142,10166,10216
3,20170317,M3,FI0050674471,SIBXH7J7,08:00:26,"41,5",1,R,NaN,NaN,NaN,NaN,NaN,NaN
4,20170317,M3,FI0050674472,FIBXH7,08:00:26,10169,1,M,NaN,20170317,10226,10142,10166,10216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15647080,20220628,M3,007647891,FIBXN2,19:59:28.277066,8188,1,M,NaN,20220715,8298,8168,8168,8189
15647081,20220628,M3,007647892,FIBXN2,19:59:44.393052,8188,1,M,NaN,20220715,8298,8168,8168,8189
15647082,20220628,M3,007647893,FIBXN2,19:59:47.739983,8186,1,M,NaN,20220715,8298,8168,8168,8189
15647083,20220628,M3,007647894,FIBXN2,19:59:54.692627,8190,1,M,NaN,20220715,8298,8168,8168,8189
15647084,20220628,M3,007647895,FIBXN2,19:59:57.914100,8189,1,M,NaN,20220715,8298,8168,8168,8189

In [ ]:
TRADE_IBEX_DATABASE[TRADE_IBEX_DATABASE["StrikePrice"].isna()]

,SessionDate,MarketCode,TradeExecID,ContractCode,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate,HighPrice,LowPrice,FirstPrice,LastPrice
0,20170317,M3,FI0050674468,FIBXH7,08:00:26,10166,1,M,NaN,20170317,10226,10142,10166,10216
1,20170317,M3,FI0050674469,FIBXJ7,08:00:26,10129,1,M,NaN,20170421,10231,10101,10129,10224
2,20170317,M3,FI0050674470,FIBXH7,08:00:26,10166,1,M,NaN,20170317,10226,10142,10166,10216
3,20170317,M3,FI0050674471,SIBXH7J7,08:00:26,"41,5",1,R,NaN,NaN,NaN,NaN,NaN,NaN
4,20170317,M3,FI0050674472,FIBXH7,08:00:26,10169,1,M,NaN,20170317,10226,10142,10166,10216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15647080,20220628,M3,007647891,FIBXN2,19:59:28.277066,8188,1,M,NaN,20220715,8298,8168,8168,8189
15647081,20220628,M3,007647892,FIBXN2,19:59:44.393052,8188,1,M,NaN,20220715,8298,8168,8168,8189
15647082,20220628,M3,007647893,FIBXN2,19:59:47.739983,8186,1,M,NaN,20220715,8298,8168,8168,8189
15647083,20220628,M3,007647894,FIBXN2,19:59:54.692627,8190,1,M,NaN,20220715,8298,8168,8168,8189
15647084,20220628,M3,007647895,FIBXN2,19:59:57.914100,8189,1,M,NaN,20220715,8298,8168,8168,8189

Estos trades no tienen ni strike ni maturity. Ver qué hacemos con ello.

In [ ]:
print(TRADE_IBEX_DATABASE)

         SessionDate MarketCode   TradeExecID ContractCode         ExecTime  \
0           20170317         M3  FI0050674468       FIBXH7         08:00:26
1           20170317         M3  FI0050674469       FIBXJ7         08:00:26
2           20170317         M3  FI0050674470       FIBXH7         08:00:26
3           20170317         M3  FI0050674471     SIBXH7J7         08:00:26
4           20170317         M3  FI0050674472       FIBXH7         08:00:26
...              ...        ...           ...          ...              ...
15647080    20220628         M3     007647891       FIBXN2  19:59:28.277066
15647081    20220628         M3     007647892       FIBXN2  19:59:44.393052
15647082    20220628         M3     007647893       FIBXN2  19:59:47.739983
15647083    20220628         M3     007647894       FIBXN2  19:59:54.692627
15647084    20220628         M3     007647895       FIBXN2  19:59:57.914100

         TradePrice Quantity TradeType StrikePrice MaturityDate HighPrice  \
0             10166        1         M         NaN     20170317     10226
1             10129        1         M         NaN     20170421     10231
2             10166        1         M         NaN     20170317     10226
3              41,5        1         R         NaN          NaN       NaN
4             10169        1         M         NaN     20170317     10226
...             ...      ...       ...         ...          ...       ...
15647080       8188        1         M         NaN     20220715      8298
15647081       8188        1         M         NaN     20220715      8298
15647082       8186        1         M         NaN     20220715      8298
15647083       8190        1         M         NaN     20220715      8298
15647084       8189        1         M         NaN     20220715      8298

         LowPrice FirstPrice LastPrice
0           10142      10166     10216
1           10101      10129     10224
2           10142      10166     10216
3             NaN        NaN       NaN
4           10142      10166     10216
...           ...        ...       ...
15647080     8168       8168      8189
15647081     8168       8168      8189
15647082     8168       8168      8189
15647083     8168       8168      8189
15647084     8168       8168      8189

[15647085 rows x 14 columns]

----------------------------

# Construcción OPTIONS_TRADE_IBEX_DATABASE

In [ ]:
class CONTRACT_TYPE(Enum):
    FUTURE = "FUTURE"
    OPTION = "OPTION"

In [ ]:
def filtered_contracts_with_trades(
        contract_type: str
) -> pd.DataFrame:
    
    # Read CSV trades with contracts
    file = Path("raw_data/TRADE_IBEX_DATABASE.csv")
    df = pd.read_csv(
        file,
        delimiter=";",
        header=0,
        dtype="string",
    )

    # Filter by contract type
    if contract_type == CONTRACT_TYPE.FUTURE:
        prefixes = ("FIBX",)
        contract_column_new = "FutureContractCode"
        filename_prefix = "FUTURE"
    elif contract_type == CONTRACT_TYPE.OPTION:
        prefixes = ("CIBX", "PIBX")
        contract_column_new = "OptionContractCode"
        filename_prefix = "OPTIONS"
    else:
        raise ValueError(f"Tipo de contrato desconocido: {contract_type}")

    # Apply filter
    df = df[df['ContractCode'].str.startswith(prefixes, na=False)]

    # Change column names
    df.rename(columns={"ContractCode": contract_column_new}, inplace=True)

    # Save CSV
    output_dir = Path(f"raw_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / f"{filename_prefix}_TRADE_IBEX_DATABASE.csv"
    df.to_csv(output_file, index=False, encoding="utf-8", sep=";")

    print(f"\nArchivo guardado en: {output_file}")
    print(f"Total filas finales: {len(df)}")

    return df

In [ ]:
df_futures = filtered_contracts_with_trades(CONTRACT_TYPE.FUTURE)
df_options = filtered_contracts_with_trades(CONTRACT_TYPE.OPTION)

Archivo guardado en: raw_data\FUTURE_TRADE_IBEX_DATABASE.csv
Total filas finales: 16039782

Archivo guardado en: raw_data\OPTIONS_TRADE_IBEX_DATABASE.csv
Total filas finales: 488705

In [ ]:
df_futures.isna().sum()

SessionDate                  0
MarketCode                   0
TradeExecID                  0
FutureContractCode           0
ExecTime                     0
TradePrice                   0
Quantity                     0
TradeType                    0
StrikePrice           16039782
MaturityDate            544847
dtype: int64

In [ ]:
# Filtrar los futuros que tienen MaturityDate vacío
df_futures_missing = df_futures[df_futures["MaturityDate"].isna()]

# Mostrar
# display(df_futures_missing)

# Valores únicos de SessionDate
unique_session_dates = df_futures_missing["SessionDate"].unique()

# Mostrar
print(unique_session_dates)
print(f"Total de fechas únicas: {len(unique_session_dates)}")

<StringArray>
['2017-01-02', '2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
 '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12', '2017-01-13',
 '2017-01-16', '2017-01-17', '2017-01-18', '2017-01-19', '2017-01-20',
 '2017-01-23', '2017-01-24', '2017-01-25', '2017-01-26', '2017-01-27',
 '2017-01-30', '2017-01-31', '2017-02-01', '2017-02-02', '2017-02-03',
 '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09', '2017-02-10',
 '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16', '2017-02-17',
 '2017-02-20', '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24',
 '2017-02-27', '2017-02-28', '2017-03-01', '2017-03-02', '2017-03-03',
 '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09', '2017-03-10',
 '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-20',
 '2018-01-31', '2018-10-01']
Length: 57, dtype: string
Total de fechas únicas: 57

In [ ]:
import pandas as pd
from pathlib import Path

# Leer CSV completo de futuros
futures_file = Path("raw_data/FUTURE_TRADE_IBEX_DATABASE.csv")
df_futures = pd.read_csv(futures_file, delimiter=";", dtype="string")

# 1️⃣ Encontrar los contract codes con MaturityDate faltante
missing_maturity_codes = df_futures.loc[
    df_futures["MaturityDate"].isna(), "FutureContractCode"
].unique()

print(f"Contract codes con MaturityDate vacío: {len(missing_maturity_codes)}")

# ➡ Guardar número de filas que tenían MaturityDate vacío antes
rows_missing_before = df_futures["MaturityDate"].isna().sum()
print(f"Filas con MaturityDate vacío antes del rellenado: {rows_missing_before}")

# 2️⃣ Crear un diccionario con los MaturityDate conocidos para cada contrato
maturity_map = (
    df_futures.loc[df_futures["MaturityDate"].notna()]
    .groupby("FutureContractCode")["MaturityDate"]
    .first()  # toma el primer valor que no sea NaN
    .to_dict()
)

# 3️⃣ Rellenar los MaturityDate faltantes usando el diccionario
mask_missing = df_futures["FutureContractCode"].isin(missing_maturity_codes)
df_futures.loc[mask_missing, "MaturityDate"] = df_futures.loc[mask_missing, "FutureContractCode"].map(maturity_map)

# 4️⃣ Comprobar que ya no hay NaN para esos contract codes
remaining_missing = df_futures.loc[
    df_futures["FutureContractCode"].isin(missing_maturity_codes) & df_futures["MaturityDate"].isna()
]
print(f"Quedan filas sin MaturityDate: {len(remaining_missing)}")

# ➡ Mostrar cuántas filas se rellenaron
rows_filled = rows_missing_before - len(remaining_missing)
print(f"Filas rellenadas: {rows_filled}")

# Opcional: mostrar algunas filas corregidas
print(df_futures[df_futures["FutureContractCode"].isin(missing_maturity_codes)].head(10))

Contract codes con MaturityDate vacío: 13
Filas con MaturityDate vacío antes del rellenado: 544847
Quedan filas sin MaturityDate: 303215
Filas rellenadas: 241632
  SessionDate MarketCode   TradeExecID FutureContractCode  \
0  2017-01-02         M3  FI0050130697             FIBXF7
1  2017-01-02         M3  FI0050130698             FIBXF7
2  2017-01-02         M3  FI0050130699             FIBXF7
3  2017-01-02         M3  FI0050130700             FIBXF7
4  2017-01-02         M3  FI0050130701             FIBXF7
5  2017-01-02         M3  FI0050130702             FIBXF7
6  2017-01-02         M3  FI0050130703             FIBXF7
7  2017-01-02         M3  FI0050130704             FIBXF7
8  2017-01-02         M3  FI0050130705             FIBXF7
9  2017-01-02         M3  FI0050130706             FIBXF7

              ExecTime TradePrice Quantity TradeType StrikePrice MaturityDate
0  1900-01-01 09:00:06     9296.0        6         M        <NA>         <NA>
1  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
2  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
3  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
4  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
5  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
6  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
7  1900-01-01 09:00:06     9296.0        6         M        <NA>         <NA>
8  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>
9  1900-01-01 09:00:06     9296.0        1         M        <NA>         <NA>

In [ ]:
missing_maturity_codes

<StringArray>
['FIBXF7', 'FIBXG7', 'FIBXH7', 'FIBXM7', 'FIBXJ7', 'FIBXZ0', 'FIBXZ1',
 'FIBXK7', 'FIBXG8', 'FIBXH8', 'FIBXV8', 'FIBXZ8', 'FIBXX8']
Length: 13, dtype: string

In [ ]:
import pandas as pd
from pathlib import Path

# Leer CSV completo de opciones
options_file = Path("raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv")
df_options = pd.read_csv(options_file, delimiter=";", dtype="string")

# 1️⃣ Encontrar los contract codes de opciones con MaturityDate faltante
missing_maturity_codes = df_options.loc[
    df_options["MaturityDate"].isna(), "OptionContractCode"
].unique()

print(f"Contract codes de opciones con MaturityDate vacío: {len(missing_maturity_codes)}")

# ➡ Guardar número de filas que tenían MaturityDate vacío antes
rows_missing_before = df_options["MaturityDate"].isna().sum()
print(f"Filas con MaturityDate vacío antes del rellenado: {rows_missing_before}")

# 2️⃣ Crear un diccionario con los MaturityDate conocidos para cada contrato
maturity_map = (
    df_options.loc[df_options["MaturityDate"].notna()]
    .groupby("OptionContractCode")["MaturityDate"]
    .first()  # toma el primer valor que no sea NaN
    .to_dict()
)

# 3️⃣ Rellenar los MaturityDate faltantes usando el diccionario
mask_missing = df_options["OptionContractCode"].isin(missing_maturity_codes)
df_options.loc[mask_missing, "MaturityDate"] = df_options.loc[mask_missing, "OptionContractCode"].map(maturity_map)

# 4️⃣ Comprobar que ya no hay NaN para esos contract codes
remaining_missing = df_options.loc[
    df_options["OptionContractCode"].isin(missing_maturity_codes) & df_options["MaturityDate"].isna()
]
print(f"Quedan filas de opciones sin MaturityDate: {len(remaining_missing)}")

# ➡ Mostrar cuántas filas se rellenaron
rows_filled = rows_missing_before - len(remaining_missing)
print(f"Filas rellenadas: {rows_filled}")

# Opcional: mostrar algunas filas corregidas
print(df_options[df_options["OptionContractCode"].isin(missing_maturity_codes)].head(10))

Contract codes de opciones con MaturityDate vacío: 749
Filas con MaturityDate vacío antes del rellenado: 24493
Quedan filas de opciones sin MaturityDate: 11610
Filas rellenadas: 12883
  SessionDate MarketCode   TradeExecID OptionContractCode  \
0  2017-01-02         M3  OM0001645362       PIBX 5100Z17
1  2017-01-02         M3  OM0001645363       CIBX 9600F17
2  2017-01-02         M3  OM0001645364       PIBX 8200F17
3  2017-01-02         M3  OM0001645366       CIBX 9300F17
4  2017-01-02         M3  OM0001645367       PIBX 8700G17
5  2017-01-02         M3  OM0001645368       PIBX 8500F17
6  2017-01-02         M3  OM0001645369       PIBX 7200H17
7  2017-01-02         M3  OM0001645370       CIBX 9400F17
8  2017-01-02         M3  OM0001645371       CIBX 9400F17
9  2017-01-02         M3  OM0001645372       CIBX 9400G17

              ExecTime TradePrice Quantity TradeType StrikePrice MaturityDate
0  1900-01-01 09:03:56       33.0        1         M        <NA>   2017-12-15
1  1900-01-01 09:13:43       45.0        3         M        <NA>         <NA>
2  1900-01-01 09:23:09        3.0     5000         H        <NA>         <NA>
3  1900-01-01 09:24:08      165.0        1         M        <NA>         <NA>
4  1900-01-01 09:28:52       80.0       10         M        <NA>         <NA>
5  1900-01-01 09:29:21        9.0     5000         H        <NA>         <NA>
6  1900-01-01 09:29:25       14.0     5000         H        <NA>         <NA>
7  1900-01-01 09:32:52      123.0        1         M        <NA>         <NA>
8  1900-01-01 09:32:53      124.0        1         M        <NA>         <NA>
9  1900-01-01 09:34:50      210.0        1         M        <NA>         <NA>

In [ ]:
# Read raw_data
TRADE_IBEX_DATABASE_df = pd.read_csv("raw_data/TRADE_IBEX_DATABASE.csv")

# Create OPTIONS_TRADE_IBEX_DATABASE
OPTIONS_TRADE_IBEX_DATABASE = TRADE_IBEX_DATABASE_df.loc[:,[
    "ContractCode",
    "SessionDate",
    "MarketCode",
    "TradeExecID",
    "ExecTime",
    "TradePrice",
    "Quantity",
    "TradeType",
    "StrikePrice",
    "MaturityDate"
]]

# Only options of IBEX
filter_options_IBX = OPTIONS_TRADE_IBEX_DATABASE["ContractCode"].str.startswith(
    ("CIBX", "PIBX"),
    na=False
)
OPTIONS_TRADE_IBEX_DATABASE = OPTIONS_TRADE_IBEX_DATABASE[filter_options_IBX]

# Rename de ContractCode
OPTIONS_TRADE_IBEX_DATABASE = OPTIONS_TRADE_IBEX_DATABASE.rename(columns={"ContractCode":"OptionContractCode"})

# Save CSV
output_file = Path("raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv")
OPTIONS_TRADE_IBEX_DATABASE.to_csv(output_file, index=False, encoding="utf-8")
print(f"Archivo final guardado en: {output_file}")

display(OPTIONS_TRADE_IBEX_DATABASE)

C:\Users\danir\AppData\Local\Temp\ipykernel_9372\2361308103.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  TRADE_IBEX_DATABASE_df = pd.read_csv('raw_data/TRADE_IBEX_DATABASE.csv')

Archivo final guardado en: raw_data\OPTIONS_TRADE_IBEX_DATABASE.csv

,OptionContractCode,SessionDate,MarketCode,TradeExecID,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate
533,PIBX 6000U17,20170317,M3,OM0001668996,09:00:24,14,4,M,6000.0,20170915.0
834,PIBX10100H17,20170317,M3,OM0001668997,09:04:05,8,1,M,10100.0,20170317.0
1011,PIBX 8000Z17,20170317,M3,OM0001668998,09:08:04,160,1,M,8000.0,20171215.0
1059,PIBX10200J17,20170317,M3,OM0001668999,09:09:02,220,1,M,10200.0,20170421.0
1060,PIBX10100H17,20170317,M3,OM0001669000,09:09:02,6,1,M,10100.0,20170317.0
...,...,...,...,...,...,...,...,...,...,...
15645193,CIBX 8500N22,20220628,M3,100144011,17:28:12.120873,52,1,M,8500.0,20220715.0
15645195,PIBX 7500N22,20220628,M3,100144012,17:28:21.709970,11,1,M,7500.0,20220715.0
15645305,CIBX 8500N22,20220628,M3,100144013,17:29:39.189409,49,1,M,8500.0,20220715.0
15645339,CIBX 8500N22,20220628,M3,100144014,17:29:58.629091,49,3,M,8500.0,20220715.0
15645392,CIBX 8500N22,20220628,M3,100144015,17:30:45.051696,49,1,M,8500.0,20220715.0

----------------------------

# Construcción FUTURE_TRADE_IBEX_DATABASE

In [ ]:
# Read raw_data
TRADE_IBEX_DATABASE_df = pd.read_csv("raw_data/TRADE_IBEX_DATABASE.csv")

# Create FUTURE_TRADE_IBEX_DATABASE
FUTURE_TRADE_IBEX_DATABASE = TRADE_IBEX_DATABASE_df.loc[:,[
    "ContractCode",
    "SessionDate",
    "MarketCode",
    "TradeExecID",
    "ExecTime",
    "TradePrice",
    "Quantity",
    "TradeType",
    "StrikePrice",
    "MaturityDate"
]]

# Only futures of IBEX
filter_futures_IBX = FUTURE_TRADE_IBEX_DATABASE["ContractCode"].str.startswith(
    ("FIBX"),
    na=False
)
FUTURE_TRADE_IBEX_DATABASE = FUTURE_TRADE_IBEX_DATABASE[filter_futures_IBX]

# Rename de ContractCode
FUTURE_TRADE_IBEX_DATABASE = FUTURE_TRADE_IBEX_DATABASE.rename(columns={"ContractCode":"FutureContractCode"})

# Save CSV
output_file = Path("raw_data/FUTURE_TRADE_IBEX_DATABASE.csv")
FUTURE_TRADE_IBEX_DATABASE.to_csv(output_file, index=False, encoding="utf-8")
print(f"Archivo final guardado en: {output_file}")

display(FUTURE_TRADE_IBEX_DATABASE)

C:\Users\danir\AppData\Local\Temp\ipykernel_9372\1047499592.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  TRADE_IBEX_DATABASE_df = pd.read_csv('raw_data/TRADE_IBEX_DATABASE.csv')

Archivo final guardado en: raw_data\FUTURE_TRADE_IBEX_DATABASE.csv

,FutureContractCode,SessionDate,MarketCode,TradeExecID,ExecTime,TradePrice,Quantity,TradeType,StrikePrice,MaturityDate
0,FIBXH7,20170317,M3,FI0050674468,08:00:26,10166,1,M,NaN,20170317.0
1,FIBXJ7,20170317,M3,FI0050674469,08:00:26,10129,1,M,NaN,20170421.0
2,FIBXH7,20170317,M3,FI0050674470,08:00:26,10166,1,M,NaN,20170317.0
4,FIBXH7,20170317,M3,FI0050674472,08:00:26,10169,1,M,NaN,20170317.0
5,FIBXJ7,20170317,M3,FI0050674473,08:00:26,10127,1,M,NaN,20170421.0
...,...,...,...,...,...,...,...,...,...,...
15647080,FIBXN2,20220628,M3,7647891,19:59:28.277066,8188,1,M,NaN,20220715.0
15647081,FIBXN2,20220628,M3,7647892,19:59:44.393052,8188,1,M,NaN,20220715.0
15647082,FIBXN2,20220628,M3,7647893,19:59:47.739983,8186,1,M,NaN,20220715.0
15647083,FIBXN2,20220628,M3,7647894,19:59:54.692627,8190,1,M,NaN,20220715.0
15647084,FIBXN2,20220628,M3,7647895,19:59:57.914100,8189,1,M,NaN,20220715.0

----------------------------

# Construcción OPTIONS_UNDERLYING_IBEX_DATABASE

In [ ]:

from pathlib import Path
import pandas as pd

In [ ]:
def build_options_underlying_ibex_database():
    # Read CSVs
    options_trade_ibex_file = Path("raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv")
    future_trade_ibex_file = Path("raw_data/FUTURE_TRADE_IBEX_DATABASE.csv")

    # Load dataframes
    options_df = pd.read_csv(
        options_trade_ibex_file,
        delimiter=";",
        header=0,
        dtype="string",
    )
    future_df = pd.read_csv(
        future_trade_ibex_file,
        delimiter=";",
        header=0,
        dtype="string",
    )

    # Select relevant columns
    options_df = options_df[["OptionContractCode", "MaturityDate"]]


    # Drop duplicates in future_df to avoid multiple matches when merging with options_df
    future_maturity_df = future_df[["FutureContractCode", "MaturityDate"]].drop_duplicates(subset=["MaturityDate"])

    # Merge
    df = options_df.merge(
        future_maturity_df,
        how="left",
        on="MaturityDate",
    )
    # Select relevant columns
    df = df[["OptionContractCode", "FutureContractCode", "MaturityDate"]]

    # Save CSV
    output_file = Path("raw_data/OPTIONS_UNDERLYING_IBEX_DATABASE.csv")
    df.to_csv(output_file, index=False, encoding="utf-8", sep=";")

    print(f"\nArchivo guardado en: {output_file}")
    print(f"Total filas finales: {len(df)}")

    return df

In [ ]:
_ = build_options_underlying_ibex_database()

Archivo guardado en: raw_data\OPTIONS_UNDERLYING_IBEX_DATABASE.csv
Total filas finales: 488705

In [ ]:
# Unique options contract codes and their maturity dates
options_maturity_df = OPTIONS_TRADE_IBEX_DATABASE.loc[:,["OptionContractCode","MaturityDate"]].drop_duplicates(subset=["OptionContractCode"], keep="first")
print(f"Options maturity DataFrame shape: {options_maturity_df.shape}")

# Unique futures contract codes and their maturity dates
futures_maturity_df = FUTURE_TRADE_IBEX_DATABASE.loc[:,["FutureContractCode","MaturityDate"]].drop_duplicates(subset=["FutureContractCode"], keep="first")
print(f"Futures maturity DataFrame shape: {futures_maturity_df.shape}")

# Merge
OPTIONS_UNDERLYING_IBEX_DATABASE  = options_maturity_df.merge(
    futures_maturity_df,
    how="left",
    on = "MaturityDate"
)

# Order
column_order = ["OptionContractCode", "FutureContractCode", "MaturityDate"]
OPTIONS_UNDERLYING_IBEX_DATABASE = OPTIONS_UNDERLYING_IBEX_DATABASE[column_order]

# Save CSV
output_file = Path("raw_data/OPTIONS_UNDERLYING_IBEX_DATABASE.csv")
OPTIONS_UNDERLYING_IBEX_DATABASE.to_csv(output_file, index=False, encoding="utf-8")
print(f"Archivo final guardado en: {output_file}")

display(OPTIONS_UNDERLYING_IBEX_DATABASE)

Options maturity DataFrame shape: (8527, 2)
Futures maturity DataFrame shape: (70, 2)
Archivo final guardado en: raw_data\OPTIONS_UNDERLYING_IBEX_DATABASE.csv

     OptionContractCode FutureContractCode  MaturityDate
0          PIBX 6000U17             FIBXU7    20170915.0
1          PIBX10100H17             FIBXH7    20170317.0
2          PIBX 8000Z17             FIBXZ7    20171215.0
3          PIBX10200J17             FIBXJ7    20170421.0
4          CIBX10000J17             FIBXJ7    20170421.0
...                 ...                ...           ...
8522     CIBX 8600W4N22                NaN    20220722.0
8523       CIBX 7500H23                NaN    20230317.0
8524     PIBX 7500W4N22                NaN    20220722.0
8525     CIBX 8800W4N22                NaN    20220722.0
8526     PIBX 8400W4N22                NaN    20220722.0

[8527 rows x 3 columns]

Hay alguno con valores missing. ¿Eliminamos esa data?

# Construcción OPTIONS_TRADE_IBEX_DATABASE

In [ ]:
def build_trades_with_underlaying():
    # Read CSVs
    options_df  = pd.read_csv(
        "raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv",
        delimiter=";",
        header=0,
        dtype="string",
    )
    futures_df  = pd.read_csv(
        "raw_data/FUTURE_TRADE_IBEX_DATABASE.csv",
        delimiter=";",
        header=0,
        dtype="string",
    )
    options_underlying_df  = pd.read_csv(
        "raw_data/OPTIONS_UNDERLYING_IBEX_DATABASE.csv",
        delimiter=";",
        header=0,
        dtype="string"
    )

    # Create exec_datetime (SessionDate + ExecTime)
    for df in (options_df, futures_df):
        df["ExecTime"] = df["ExecTime"].astype(str).str.split().str[-1]
        
        # Añadir .000000 a los que no tienen microsegundos
        df["ExecTime"] = df["ExecTime"].apply(
            lambda x: x if "." in x else x + ".000000"
        )

        df["exec_datetime"] = pd.to_datetime(
            df["SessionDate"].astype(str) + " " + df["ExecTime"],
            format="%Y-%m-%d %H:%M:%S.%f",
        )

        df["exec_datetime"] = pd.to_datetime(
            df["SessionDate"].astype(str) + " " + df["ExecTime"]
        )

    # Rename exec_datetime of future
    futures_df = futures_df.rename(columns={"exec_datetime": "exec_datetime_future"})

    # Join option with its underlying future
    options_df = options_df.merge(
        options_underlying_df,
        on="OptionContractCode",
        how="left"
    )

    # Order by exec_datetime
    options_df = options_df.sort_values("exec_datetime").reset_index(drop=True)
    futures_df = futures_df.sort_values("exec_datetime_future").reset_index(drop=True)

    # As-of join: Last trade of the underlying FUTURE with exec_datetime <= exec_datetime of the option
    df = pd.merge_asof(
        options_df,
        futures_df,
        by="FutureContractCode",
        left_on="exec_datetime",
        right_on="exec_datetime_future",
        direction="backward",
        suffixes=("", "_future")
    )

    # Rename columns
    df = df.rename(columns={
        "TradePrice": "TradePrice_option",
        "TradePrice_future": "underelayingPrice",
        "exec_datetime_future": "underelayingExecTime"
    })

    # Select final columns
    df = df[[
        "OptionContractCode",
        "FutureContractCode",
        "underelayingPrice",
        "SessionDate",
        "MarketCode",
        "TradeExecID",
        "ExecTime",
        "TradePrice_option",
        "Quantity",
        "TradeType",
        "StrikePrice",
        "MaturityDate",
        "exec_datetime",
        "underelayingExecTime"
    ]]

    # Save CSV
    output_file = Path("raw_data/OPTIONS_TRADE_UNDERLYING_IBEX_DATABASE.csv")
    df.to_csv(output_file, index=False, encoding="utf-8", sep=";")

    print(f"\nArchivo guardado en: {output_file}")
    print(f"Total filas finales: {len(df)}")

    return df

In [ ]:
_ = build_trades_with_underlaying()

Archivo guardado en: raw_data\OPTIONS_TRADE_UNDERLYING_IBEX_DATABASE.csv
Total filas finales: 122990031

In [ ]:
import pandas as pd
from pathlib import Path

# Read raw data
options_df  = pd.read_csv("raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv")
futures_df  = pd.read_csv("raw_data/FUTURE_TRADE_IBEX_DATABASE.csv")
options_underlying_df  = pd.read_csv("raw_data/OPTIONS_UNDERLYING_IBEX_DATABASE.csv")

# Create exec_datetime (SessionDate + ExecTime)
for df in (options_df, futures_df):
    df["SessionDate"] = df["SessionDate"].astype(str)
    df["ExecTime"] = df["ExecTime"].astype(str)

    df["exec_datetime"] = pd.to_datetime(
        df["SessionDate"] + " " + df["ExecTime"],
        format="mixed"
    )

# Join option with its underlying future
options_df = options_df.merge(
    options_underlying_df,
    on="OptionContractCode",
    how="left"
)

# Rename exec_datetime of future
futures_df = futures_df.rename(columns={"exec_datetime": "exec_datetime_future"})

# Order by exec_datetime
options_df = options_df.sort_values("exec_datetime").reset_index(drop=True)
futures_df = futures_df.sort_values("exec_datetime_future").reset_index(drop=True)

# As-of join: Last trade of the underlying FUTURE with exec_datetime <= exec_datetime of the option
OPTIONS_TRADE_IBEX_DATABASE = pd.merge_asof(
    options_df,
    futures_df,
    by="FutureContractCode",
    left_on="exec_datetime",
    right_on="exec_datetime_future",
    direction="backward",
    suffixes=("", "_future")
)

# Rename columns
OPTIONS_TRADE_IBEX_DATABASE = OPTIONS_TRADE_IBEX_DATABASE.rename(columns={
    "TradePrice": "TradePrice_option",
    "TradePrice_future": "underelayingPrice",
    "exec_datetime_future": "underelayingExecTime"
})

# Select final columns
OPTIONS_TRADE_IBEX_DATABASE = OPTIONS_TRADE_IBEX_DATABASE[[
    "OptionContractCode",
    "FutureContractCode",
    "underelayingPrice",
    "SessionDate",
    "MarketCode",
    "TradeExecID",
    "ExecTime",
    "TradePrice_option",
    "Quantity",
    "TradeType",
    "StrikePrice",
    "MaturityDate",
    "exec_datetime",
    "underelayingExecTime"
]]

# Save CSV
output_file = Path("raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv")
OPTIONS_TRADE_IBEX_DATABASE.to_csv(output_file, index=False, encoding="utf-8")
print(f"Archivo final guardado en: {output_file}")

display(OPTIONS_TRADE_IBEX_DATABASE)

C:\Users\danir\AppData\Local\Temp\ipykernel_29552\2085366734.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  options_df  = pd.read_csv('raw_data/OPTIONS_TRADE_IBEX_DATABASE.csv')
C:\Users\danir\AppData\Local\Temp\ipykernel_29552\2085366734.py:6: DtypeWarning: Columns (3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  futures_df  = pd.read_csv('raw_data/FUTURE_TRADE_IBEX_DATABASE.csv')

Archivo final guardado en: raw_data\OPTIONS_TRADE_IBEX_DATABASE.csv

,OptionContractCode,FutureContractCode,underelayingPrice,SessionDate,MarketCode,TradeExecID,ExecTime,TradePrice_option,Quantity,TradeType,StrikePrice,MaturityDate,exec_datetime,underelayingExecTime
0,PIBX 6000U17,FIBXU7,NaN,20170317,M3,OM0001668996,09:00:24,14,4,M,6000.0,NaN,2017-03-17 09:00:24.000000,NaT
1,PIBX10100H17,FIBXH7,10154,20170317,M3,OM0001668997,09:04:05,8,1,M,10100.0,20170317.0,2017-03-17 09:04:05.000000,2017-03-17 09:03:02.000000
2,PIBX 8000Z17,FIBXZ7,NaN,20170317,M3,OM0001668998,09:08:04,160,1,M,8000.0,NaN,2017-03-17 09:08:04.000000,NaT
3,PIBX10200J17,FIBXJ7,10129,20170317,M3,OM0001668999,09:09:02,220,1,M,10200.0,20170421.0,2017-03-17 09:09:02.000000,2017-03-17 09:09:02.000000
4,PIBX10100H17,FIBXH7,10170,20170317,M3,OM0001669000,09:09:02,6,1,M,10100.0,20170317.0,2017-03-17 09:09:02.000000,2017-03-17 09:09:02.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422867,CIBX 8500N22,FIBXN2,8227,20220628,M3,100144011,17:28:12.120873,52,1,M,8500.0,20220715.0,2022-06-28 17:28:12.120873,2022-06-28 17:28:10.680029
422868,PIBX 7500N22,FIBXN2,8227,20220628,M3,100144012,17:28:21.709970,11,1,M,7500.0,20220715.0,2022-06-28 17:28:21.709970,2022-06-28 17:28:13.814459
422869,CIBX 8500N22,FIBXN2,8225,20220628,M3,100144013,17:29:39.189409,49,1,M,8500.0,20220715.0,2022-06-28 17:29:39.189409,2022-06-28 17:29:39.083192
422870,CIBX 8500N22,FIBXN2,8226,20220628,M3,100144014,17:29:58.629091,49,3,M,8500.0,20220715.0,2022-06-28 17:29:58.629091,2022-06-28 17:29:58.586608
422871,CIBX 8500N22,FIBXN2,8224,20220628,M3,100144015,17:30:45.051696,49,1,M,8500.0,20220715.0,2022-06-28 17:30:45.051696,2022-06-28 17:30:44.729817

In [ ]:
import pandas as pd
from pathlib import Path

# Leer CSV
options_underlying_file = Path("raw_data/OPTIONS_UNDERLYING_IBEX_DATABASE.csv")
options_underlying_df = pd.read_csv(options_underlying_file, delimiter=";", dtype="string")

# Contar futuros distintos por cada opción y ordenar de mayor a menor
future_counts = (
    options_underlying_df
    .groupby("OptionContractCode")["FutureContractCode"]
    .nunique()
    .reset_index()
    .rename(columns={"FutureContractCode": "num_futures"})
    .sort_values("num_futures", ascending=False)
)

# Mostrar por pantalla
display(future_counts)

     OptionContractCode  num_futures
8997       PIBX11500Z17            2
4525       PIBX 6600Z17            2
4550       PIBX 6700U17            2
9027       PIBX12500M17            2
4489       PIBX 6600U17            2
...                 ...          ...
4562     PIBX 6700W1V20            0
4561     PIBX 6700W1U20            0
4560     PIBX 6700W1Q20            0
4559     PIBX 6700W1N20            0
4558     PIBX 6700W1M20            0

[9030 rows x 2 columns]